export const lines = [
	{
		id: "red",
		title: "Red",
		abbr: "RD",
		color: "bg-red-500",
		borderColor: "border-red-600",
		textColor: "text-red-500",
		stationStart: "Shady Grove",
		stationEnd: "Glenmont",
	},
	{
		id: "green",
		title: "Green",
		abbr: "GR",
		color: "bg-green-500",
		borderColor: "border-green-600",
		textColor: "text-green-500",
		stationStart: "Greenbelt",
		stationEnd: "Branch Ave.",
	},

	{
		id: "yellow",
		title: "Yellow",
		abbr: "YL",
		color: "bg-yellow-400",
		borderColor: "border-yellow-500",
		textColor: "text-yellow-400",
		stationStart: "Mt. Vernon Square",
		stationEnd: "Huntington",
	},
	{
		id: "blue",
		title: "Blue",
		abbr: "BL",
		color: "bg-blue-500",
		borderColor: "border-blue-600",
		textColor: "text-blue-500",
		stationStart: "Franconia-Springfield",
		stationEnd: "Downtown Largo",
	},
	{
		id: "orange",
		title: "Orange",
		abbr: "OR",
		color: "bg-orange-500",
		borderColor: "border-orange-600",
		textColor: "text-orange-500",
		stationStart: "Vienna",
		stationEnd: "New Carrolton",
	},
	{
		id: "silver",
		title: "Silver",
		abbr: "SV",
		color: "bg-gray-500",
		borderColor: "border-gray-600",
		textColor: "text-gray-500",
		stationStart: "Ashburn",
		stationEnd: "Largo Town Center",
	},
];
