export const lines = [
	{
		id: "RD",
		title: "Red Line",
		name: "Red Line",
		abbr: "RD",
		color: "bg-red-500",
		borderColor: "border-red-600",
		textColor: "text-red-500",
		stationStart: "A15",
		stationEnd: "B11",
	},
	{
		id: "BL",
		title: "Blue Line",
		name: "Blue Line",
		abbr: "BL",
		color: "bg-blue-500",
		borderColor: "border-blue-600",
		textColor: "text-blue-500",
		stationStart: "J03",
		stationEnd: "G05",
	},
	{
		id: "YL",
		title: "Yellow Line",
		name: "Yellow Line",
		abbr: "YL",
		color: "bg-yellow-400",
		borderColor: "border-yellow-500",
		textColor: "text-yellow-400",
		stationStart: "C15",
		stationEnd: "E06",
	},
	{
		id: "OR",
		title: "Orange Line",
		name: "Orange Line",
		abbr: "OR",
		color: "bg-orange-500",
		borderColor: "border-orange-600",
		textColor: "text-orange-500",
		stationStart: "K08",
		stationEnd: "D13",
	},
	{
		id: "GR",
		title: "Green Line",
		name: "Green Line",
		abbr: "GR",
		color: "bg-green-500",
		borderColor: "border-green-600",
		textColor: "text-green-500",
		stationStart: "F11",
		stationEnd: "E10",
	},
	{
		id: "SV",
		title: "Silver Line",
		name: "Silver Line",
		abbr: "SV",
		color: "bg-gray-500",
		borderColor: "border-gray-600",
		textColor: "text-gray-500",
		stationStart: "N06",
		stationEnd: "G05",
	},
] as const;
