export const lines = [
	{
		id: "RD",
		route_id: "RED",
		title: "Red Line",
		name: "Red Line",
		abbr: "RD",
		color: "bg-red-500",
		borderColor: "border-red-600",
		textColor: "text-red-500",
		stationStartName: "A15",
		stationEndName: "B11",
	},
	{
		id: "BL",
		route_id: "BLUE",
		title: "Blue Line",
		name: "Blue Line",
		abbr: "BL",
		color: "bg-blue-500",
		borderColor: "border-blue-600",
		textColor: "text-blue-500",
		stationStartName: "J03",
		stationEndName: "G05",
	},
	{
		id: "YL",
		route_id: "YELLOW",
		title: "Yellow Line",
		name: "Yellow Line",
		abbr: "YL",
		color: "bg-yellow-400",
		borderColor: "border-yellow-500",
		textColor: "text-yellow-400",
		stationStartName: "C15",
		stationEndName: "E06",
	},
	{
		id: "OR",
		route_id: "ORANGE",
		title: "Orange Line",
		name: "Orange Line",
		abbr: "OR",
		color: "bg-orange-500",
		borderColor: "border-orange-600",
		textColor: "text-orange-500",
		stationStartName: "K08",
		stationEndName: "D13",
	},
	{
		id: "GR",
		route_id: "GREEN",
		title: "Green Line",
		name: "Green Line",
		abbr: "GR",
		color: "bg-green-500",
		borderColor: "border-green-600",
		textColor: "text-green-500",
		stationStartName: "F11",
		stationEndName: "E10",
	},
	{
		id: "SV",
		route_id: "SILVER",
		title: "Silver Line",
		name: "Silver Line",
		abbr: "SV",
		color: "bg-gray-500",
		borderColor: "border-gray-600",
		textColor: "text-gray-500",
		stationStartName: "N06",
		stationEndName: "G05",
	},
] as const;
